language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_install:
  - sudo ./tests/kafka-0.9.0/setup.sh --broker-id 1 --broker-list localhost --host-name localhost --force-download
  - sudo service zookeeper start
  - sudo service kafka start
install:
  - composer install
script: phpunit -c build
